# In this notebook, we're going to cover some of the most fundamental concepts of Tensorflow.

* Introduction to tensors
* Getting information from tensors
* Manipulating Tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up regular Python functions)
* Using GPU's with tensorflow


In [1]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [7]:
# Creating a matrix (more than one dimension)
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
matrix.ndim

2

In [10]:
another_matrix = tf.constant([[1.,2.],[3.,4.],[5.,6.]],
                             dtype=tf.float16)

# By default it is float32
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
# Let's create a tensor 

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]
                       ])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

What we've created so far

* Scalar : a single number 
* Vector : a number with direction 
* Matrix : 2-d array of numbers
* Tensor : an n-dimentional array of numbers (where n can be any number. 0-dim tensor is a scalar)


# Creating tensors with `tf.Variable`

In [14]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
changable_tensor[0] = 7

TypeError: ignored

In [16]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
unchangable_tensor[0].assign(7)
unchangable_tensor

# This will not work because you're working with constant

AttributeError: ignored

### Creating random tensors

Random tensors are tensors of some arbitrary size with random numbers

In [32]:
# Creating 2 random (but the same) random tensors 

random_1 = tf.random.Generator.from_seed(42) # setting seed for reproducability
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1 == random_2
# Normal will generate numbers from a uniform distribution

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [ True,  True]])>

### Shuffling the orders of elements in a tensor

This is important so that the inherent order in the training data doesn't affect the model

In [33]:
not_shuffled = tf.constant(
    [[1,2],
     [3,4],
     [5,6]
    ]
)

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [39]:
tf.random.set_seed(42) # Global level seed 
tf.random.shuffle(not_shuffled, seed=42) # Operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

### Creating Tensors from Numpy

In [41]:
tf.ones([5,10]) 

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [42]:
tf.zeros(shape=(5,10))

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [43]:
# Turning Numpy arrays into tensors

# Tensors can be run on GPUs for much faster computation 

In [50]:
import numpy as np
numpy_A = np.arange(1,25)
numpy_A, numpy_A.shape

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]), (24,))

In [51]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>, <tf.Tensor: shape=(24,), dtype=int64, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

## Getting information from Tensors

* Shape `tensor.shape`
* Rank - Number of tensor dimensions `tensor.ndim`
* Axis `tensor[0]. or tensor[1]`
* Size `tf.size(tensor)`

In [52]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [54]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [62]:
# Getting various attributes of our tensor 

print("Data type of every element: ", rank_4_tensor.dtype)
print("Elements along the 0th axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
# The (0,1,2,3) axis refers to (2,3,4,5)
print("Size of our tensor: ", tf.size(rank_4_tensor))
print("Size of our tensor: ", tf.size(rank_4_tensor).numpy())
# Do the same for the other attributes 

Data type of every element:  <dtype: 'float32'>
Elements along the 0th axis: 2
Elements along the last axis: 5
Size of our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Size of our tensor:  120


### Indexing Tensors

Tensors can be indexed just like Python lists 

In [63]:
# Getting first 2 elements of each dimensions

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [67]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [68]:
rank_4_tensor[:1, :1, :, :1].shape

TensorShape([1, 1, 4, 1])

In [69]:
# Create a rank 2 tensor 

rank_2_tensor = tf.constant([[1,2],
                             [3,4]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [71]:
some_list = [5,6,7,8]

In [75]:
# Adding an extra dimension to our rank2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

# ... means every axis before the one I'm specifying

# You could've used [:, :, tf.newaxis] as well

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [78]:
# Alternative to tf.newaxis 

tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

### Manipulating Tensors (tensor operations)

** Basic Operations **

`+`, `-`, `*`, `/`

In [79]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [80]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [81]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [82]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [84]:
# We can use the tensorflow built-in function too 

tf.multiply(tensor, 5)

# This will speed up compared to the cell above
# It is faster on a GPU/TPU

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

**Matrix Multiplication**

One of the most common tensor operations performed. 


In [86]:
# Matrix multiplication

# This is going to do the dot product
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [87]:
# This will do element wise multiplication 
tensor * tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [89]:
tensor @ tensor 
# the @ symbol can be used for dot product in python notation

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [90]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X * Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 16],
       [27, 40],
       [55, 72]], dtype=int32)>

In [91]:
X @ Y # This will not work

InvalidArgumentError: ignored

In [93]:
X @ tf.transpose(Y) # This will work

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [95]:
tf.transpose(X) @ Y # This will also work

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [96]:
# Inner dimensions of the 2 matrices must match 
# Resulting matrix will have the shape of the outer dimensions

In [99]:
tf.matmul(X, tf.reshape(X, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [101]:
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [102]:
# You should be doing matrix multiplication using transpose instead of reshape

### You can do a dotproduct using 
`tf.matmul()` or `tf.tensordot()`

In [105]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [106]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Changing the datatype

(by default, the datatype is int32 or float32 depending on how tensor was initialised)

In [111]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [112]:
D = tf.cast(C, dtype=tf.float16)
D.dtype

tf.float16

In [113]:
# Change from int32 to float32

E = tf.cast(D, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

### Aggregating Tensors 

Aggregating Tensors - condensing the values from multiple values to a smaller amount of values 

In [114]:
Agg = tf.constant([1, 2, 3, 4, 5, -6, -7, -8, -9, -10])
Agg

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  1,   2,   3,   4,   5,  -6,  -7,  -8,  -9, -10], dtype=int32)>

In [116]:
tf.abs(Agg).numpy()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [119]:
max(Agg)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [121]:
tf.math.reduce_max(Agg)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [122]:
tf.math.reduce_min(Agg)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [123]:
tf.math.reduce_mean(Agg)

<tf.Tensor: shape=(), dtype=int32, numpy=-2>

In [124]:
tf.math.reduce_sum(Agg)

<tf.Tensor: shape=(), dtype=int32, numpy=-25>

In [125]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [126]:
tf.math.reduce_sum(X)

# Takes the sum of all the element of the tensor 

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [127]:
tf.math.reduce_sum(X, axis=0)

# Row Sum

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 9, 12], dtype=int32)>

In [128]:
tf.math.reduce_sum(X, axis=1)

# Column Sum

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  7, 11], dtype=int32)>

In [129]:
# To find the variance of our tensor, we need access to tensorflow_probability

import tensorflow_probability as tfp

tfp.stats.variance(Agg)

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [130]:
tf.math.reduce_std(Agg)

TypeError: ignored

In [131]:
# The above cell wont work because it required the tensor to be 
# real or complex. So you must cast it as float 

tf.math.reduce_std(tf.cast(Agg, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=5.68>

### Finding positional max or min in tensor


In [133]:
# Creating new tensor for finding positional max and min

tf.random.set_seed(42)

F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [134]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [136]:
G = tf.random.uniform(shape=[10, 5])
G

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764],
       [0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ],
       [0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827],
       [0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506],
       [0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463],
       [0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714],
       [0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674],
       [0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ],
       [0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ],
       [0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]],
      dtype=float32)>

In [138]:
tf.argmax(G, axis=1)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 4, 2, 2, 2, 0, 3, 0, 4, 1])>

### Squeezig a tensor (removing all single dimensions)

In [140]:
# Create a tensor to get started

tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape=[1,1,1,1,1,50]))
H

<tf.Tensor: shape=(1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255,
            0.03366041, 0.68467236, 0.74011743, 0.8724445 ,
            0.22632635, 0.22319686, 0.3103881 , 0.7223358 ,
            0.13318717, 0.5480639 , 0.5746088 , 0.8996835 ,
            0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 ,
            0.6602763 , 0.33695042, 0.60141766, 0.21062577,
            0.8527372 , 0.44062173, 0.9485276 , 0.23752594,
            0.81179297, 0.5263394 , 0.494308  , 0.21612847,
            0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162,
            0.79873943, 0.66028714, 0.5871513 , 0.16461694,
            0.7381023 , 0.32054043]]]]]], dtype=float32)>

In [144]:
H.shape

TensorShape([1, 1, 1, 1, 1, 50])

In [145]:
H_squeezed = tf.squeeze(H)
H_squeezed, H_squeezed.shape

# Useful for removing single dimensions

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One hot encoding 

[Reference Link](https://machinelearningmastery.com/why-one-hot-encode-data-in-machine-learning/)

In [146]:
# Create a list of indices

some_list = [0, 1, 2, 3]

tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [148]:
# Specify custom values for one hot encoding

tf.one_hot(some_list, depth=len(some_list), on_value="GO ML", off_value="no ml")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'GO ML', b'no ml', b'no ml', b'no ml'],
       [b'no ml', b'GO ML', b'no ml', b'no ml'],
       [b'no ml', b'no ml', b'GO ML', b'no ml'],
       [b'no ml', b'no ml', b'no ml', b'GO ML']], dtype=object)>

### Squaring, Log and Square Root

In [149]:
I = tf.range(1, 10)

In [150]:
tf.square(I)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [153]:
tf.sqrt(tf.cast(I, dtype=tf.float32))


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [156]:
tf.math.log(tf.cast(I, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy

TensorFlow interacts beautifully with Numpy Arrays.

They have full interoperability.

In [159]:
J = tf.constant(np.array([1., 2., 3.]))
J.numpy()[0]

1.0

In [161]:
J[0]

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [162]:
# Default tyes of each are slightly different 
numpy_J = tf.constant(np.array([1., 2., 3.]))
tensor_J = tf.constant([1., 3., 5.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### One of the main differences between a Tensor and Numpy arrays is that Tensors can be run really fast on GPUs / TPUs.

Finding access to GPUs

In [2]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Thu May 27 21:37:48 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

If you have a CUDA enables GPU, tensorflow will automatically use it.